config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  resources :enquiries
  devise_for :users
  root 'pages#home'
  get 'pages/contact'
  get 'pages/about'

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    respond_to do |format|
      if @enquiry.save
        EnquiryMailer.response(@enquiry).deliver_now
        EnquiryMailer.received(@enquiry).deliver_now
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :subject, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/enquiries/_form.html.erb
<%= form_for(@enquiry) do |f| %>
<% if @enquiry.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@enquiry.errors.count, "error") %>
        prohibited this enquiry from being saved:</h2>

    <ul>
        <% @enquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="field">
    <p><%= f.label :name %><br></p>
    <%= f.text_field :name, {:style => 'width: 100%;', :class => "form-control"} %>
</div>
<div class="field">
    <p><%= f.label :email %><br></p>
    <%= f.text_field :email, {:style => 'width: 100%;', :class => "form-control"}  %>
</div>
<div class="field">
    <p><%= f.label :subject %><br></p>
    <%= f.text_field :subject, {:style => 'width: 100%;', :class => "form-control"}  %>
</div>
<div class="field">
    <p><%= f.label :message %><br></p>
    <%= f.text_area :message, {:style => 'width: 100%;', :class => "form-control"}  %>
</div>
<div class="actions">
    <%= f.submit 'Submit Enquiry', :class => 'btn btn-default'  %>
</div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %>
|
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.name %></td>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.subject %></td>
        <td><%= enquiry.message %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<div class='container' style='text-align: center;'>

    <h2>New Enquiry<br><br></h2>
    <div class="container">
        <div class="row row-centered lvl2" style="padding 10px; width: 100%; max-width: 90vw;">
            <div class="col-sm-3"></div>
            <div class="col-sm-6 lv2" style="padding: 10px;">
                <%= render 'form' %>

                <%= link_to 'Back', enquiries_path %>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
</div>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @enquiry.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="/manifest.json">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="msapplication-TileImage" content="/mstile-144x144.png">
        <meta name="theme-color" content="#ffffff">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.5.1/dat.gui.js" %>
        <%= csrf_meta_tags %>

        <meta charset="utf-8">
        <meta name="description" content="Jack Markham's Portfolio">
        <meta name="Author" content="Jack Markham">
        <meta name="keyword" content="Web developer, full stack programmer">
        <meta http_equiv="refresh" content="120">
        <meta name="viewport" content="width=device width, initial-scale=1.0">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Jack Markham - Development Portfolio</title>

        <link href="https://fonts.googleapis.com/css?family=Kanit:800|Press+Start+2P" rel="stylesheet">

    </head>
    <body>
        <%= render 'partials/nav' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>

    </body>
</html>

app/views/pages/about.html.erb
<center style="margin-bottom: 30px">
    <img src="http://i64.tinypic.com/10xqzgw.jpg" class="img-circle" alt="My Beautiful Face" style="height: 300px; z-index: 3; box-shadow: 5px 5px 3px black" align="center">
</center>

<center style="margin-bottom: 30px">
    <h1 style="color: white; animation-name: none; font-size: 5vw;">
        <br>Jack Markham
    </h1>
</center>

<div class="container">
    <div class="row row-centered" style="border: none; background-color: transparent; margin-bottom: 10px;">
        <div class="col-sm-1 col-centered"></div>
        <div class="col-sm-5 col-centered lvl2" style="background: #000080; margin: 20px; margin-bottom: 150px;">
            <div style="text-align: center; margin-bottom: 30px;">
                <h3><%= link_to "Get In Touch!", new_enquiry_path, {:style => 'color: white;  display: inline;'} %></h3>
            </div>

            <div id="map" style="width: 100%; height: 200px; margin-bottom: 10px;"></div>
            <script type="text/javascript">
                $(function () {
                    $("#map").googleMap({
                        zoom: 15, // Initial zoom level (optional)
                        coords: [
                            -33.8819435, 151.1952626
                        ], // Map center (optional)
                        type: "ROADMAP" // Map type (optional)

                    });
                })
            </script>
            <div style="text-align: center;">

                <div style="margin-top: 30px;">
                    <span class="glyphicon glyphicon-earphone" aria-hidden="true" style="color: white; display: inline;"></span>
                    <p style="color: white; vertical-align: middle; display: inline;">&nbsp; +61 403 517 412<br><br></p>
                </div>
                <div>
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true" style="color: white; display: inline;"></span>
                    <a href="mailto:markham.jack.w@gmail.com">
                        <p style="color: white; vertical-align: middle; display: inline;">&nbsp; markham.jack.w@gmail.com</p>
                    </a>
                </div>
                <div style="text-align: center;">

                    <div style="display: inline-block;">

                        <a href="https://www.facebook.com/jack.markham"><img src="http://i68.tinypic.com/2cd7v3a.png" class="contacticon hvr-grow-shadow"/></a>
                        <a href="https://twitter.com/"><img src="http://i67.tinypic.com/10p6jo5.png" class="contacticon hvr-grow-shadow"/></a>
                        <a href="https://github.com/jackwmarkham"><img src="http://i65.tinypic.com/rkzh93.png" class="contacticon hvr-grow-shadow"/></a>
                        <a href="https://www.linkedin.com/in/jack-markham-981644123"><img src="http://i63.tinypic.com/ncxkyh.png" class="contacticon hvr-grow-shadow"/></a>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-5 col-centered lvl2" style=" background: #000080; margin: 20px;">
            <h3 style='text-align: center;'>
                A Little Bit About Me
            </h3>
            <p>
                <br>
                Hello! My name is Jack Markham, and I’m a Sydney-based full-stack developer, specialising in front-end web development and design. Currently I am a student at CoderFactory Academy and have experience with Ruby, Rails, HTML, CSS and a little bit of
                javascript.<br><br><br>
                Prior to entering development, I graduated from the University of Sydney with a degree in in chemistry (BSc. Hons I) and spent time as a research assistant investigating potential metallo-organic drugs for cancer treatment.<br><br><br>
                I have a passion for science but found academia to be a little slow-paced and administration-heavy. I’m an avid reader, overly-invested cat owner, Seinfeld fanatic, hip hop addict and incredibly amateur musician. If you are a business or individual
                seeking a web presence, or an employer looking to hire, feel free to drop me a line!<br>
            </p>
        </div>
        <div class="col-sm-1 col-centered"></div>
    </div>
</div>

<script src="jquery.googlemap.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key= AIzaSyBCgSnctlOV7YeWUlat461Kncs57BYaJo0"></script>

<script>
    $(document).ready(function () {
        var d = new Date();
        var n = d.getHours();
        if (n > 5 && n < 7)
            document.body.className = "dawn";
        else if (n >= 8 && n <= 10)
            document.body.className = "morning";
        else if (n >= 11 && n <= 14)
            document.body.className = "midday";
        else if (n >= 15 && n <= 17)
            document.body.className = "afternoon";
        else if (n >= 18 && n <= 19)
            document.body.className = "evening";
        else if (n == 20)
            document.body.className = "sunset";
        else if (n >= 21 && n <= 24)
            document.body.className = "night";
        else if (n >= 0 && n <= 5)
            document.body.className = "midnight";
        else
            document.body.className = "midday";
        }
    );
</script>

app/views/pages/aboutbackup.html.erb
<center style="margin-bottom: 30px">
    <img src="http://i64.tinypic.com/10xqzgw.jpg" class="img-circle" alt="My Beautiful Face" style="height: 300px; z-index: 3; box-shadow: 5px 5px 3px black" align="center">
</center>

<center style="margin-bottom: 30px">
    <h1 style="color: white; animation-name: none;">
        <br>Jack Markham
    </h1>
</center>

<div class="container">
    <div class="row row-centered" style="border: none; background-color: transparent; margin-bottom: 10px;">
        <div class="col-sm-1 col-centered"></div>
        <div class="col-sm-5 col-centered lvl2" style="background: #000080; margin: 20px;">
            <div id="googleMap" style="width: 100%; height:200px; margin-top: 10px; margin-bottom: 10px;"></div>
            <div style="text-align: center;">
                <h3>Contact Details</h3>
                <div>
                    <span class="glyphicon glyphicon-earphone" aria-hidden="true" style="color: white; display: inline;"></span>
                    <p style="color: white; vertical-align: middle; display: inline;">&nbsp; +61 403 517 412<br><br></p>
                </div>
                <div>
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true" style="color: white; display: inline;"></span>
                    <a href="mailto:markham.jack.w@gmail.com"><p style="color: white; vertical-align: middle; display: inline;">&nbsp; markham.jack.w@gmail.com</p></a>
                </div>
                <div style="text-align: center;">

                    <div style="display: inline-block;">

                        <img src="http://i68.tinypic.com/2cd7v3a.png" class="contacticon"/>
                        <img src="http://i67.tinypic.com/10p6jo5.png" class="contacticon"/>
                        <img src="http://i65.tinypic.com/rkzh93.png" class="contacticon"/>
                        <img src="http://i63.tinypic.com/ncxkyh.png" class="contacticon"/>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-5 col-centered lvl2" style="display: table-cell; vertical-align: middle; background: #000080; margin: 20px;">
            <h3 style='text-align: center;'>
                About Me
            </h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis faucibus augue sit amet quam dapibus commodo. Phasellus justo eros, gravida eget ipsum commodo, interdum convallis massa. Praesent congue massa a risus gravida tempus. Fusce dui nibh,
                bibendum a lacinia sed, hendrerit at urna. Aenean ac purus condimentum, congue libero in, congue arcu. Phasellus rutrum, nunc et tempus vulputate, arcu sapien condimentum felis, consectetur condimentum risus lacus id felis. Phasellus interdum non
                tellus sed viverra. Integer dapibus vehicula feugiat. Fusce molestie neque vitae tellus suscipit, et finibus justo scelerisque. Vestibulum vel ex fermentum, volutpat lacus et, rhoncus ex. Nunc viverra lorem nec ex pharetra tempus. Mauris non dapibus
                lacus. Maecenas lorem mauris, dignissim nec orci et, lacinia hendrerit risus. Integer eget faucibus ipsum. Donec et purus ut mi tempor dapibus. Vestibulum fringilla mi commodo, finibus tortor quis, rutrum sem. Sed porta tincidunt nibh eget finibus. Doop doop doop de dooooo.

            </p>
        </div>
        <div class="col-sm-1 col-centered"></div>
    </div>
</div>
<!--dicks-->
<div style="width: 400px; max-width: 100vw; margin: auto;">
    <h3 style="text-align: center;  text-shadow: 5px 5px 3px black;">
        Enquiries
    </h3>
    <form>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group">
            <label for="Subject1">
                <p>Subject</p>
            </label>
            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Subject">
        </div>
        <div class="form-group">
            <label for="Message1">
                <p>Message</p>
            </label>
            <textarea name="message" class="form-control" style="height:150px;" placeholder="Message"></textarea>
        </div>
    </form>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key= AIzaSyBCgSnctlOV7YeWUlat461Kncs57BYaJo0"></script>

<script>
  function initialize() {
    var mapProp = {
      center:new google.maps.LatLng(-33.8819435,151.1952626),
      zoom:15,
      mapTypeId:google.maps.MapTypeId.ROADMAP
    };
    var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>


<script>
    $(document).ready(function () {
        var d = new Date();
        var n = d.getHours();
        if (n > 5 && n < 7)
            document.body.className = "dawn";
        else if (n >= 8 && n <= 10)
            document.body.className = "morning";
        else if (n >= 11 && n <= 14)
            document.body.className = "midday";
        else if (n >= 15 && n <= 17)
            document.body.className = "afternoon";
        else if (n >= 18 && n <= 19)
            document.body.className = "evening";
        else if (n == 20)
            document.body.className = "sunset";
        else if (n >= 21 && n <= 24)
            document.body.className = "night";
        else if (n >= 0 && n <= 5)
            document.body.className = "midnight";
        else
            document.body.className = "midday";
        }
    );
</script>

app/views/pages/contact.html.erb
<div>
  <h2> Contact Me </h2>
<form>
  <div class="form-group">
    <!-- <%= f.text_field :last_name, class: 'form-control' %> -->
  </div>
  <div class="form-group">
    <!-- <%= f.text_field :last_name, class: 'form-control' %> -->
  </div>
  <div class="form-group">
    <label for="Subject1"><h3>Subject</h3></label>
    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Subject">
  </div>
  <div class="form-group">
    <label for="Message1"><h3>Message</h3></label>
    <textarea name="message" class="form-control" style="height:150px;" placeholder="Message"></textarea>
  </div>
  </form>
</div>


  <footer class="footer">
        <div class="container">
          <p class="text-muted">Find me on:</p>
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          </uL>
        </div>
  </footer>

app/views/partials/_nav.html.erb
<div class="nav-div">
    <a href="/" data-no-turbolink>
        <button type="button" class="btn btn-default logo-box"></button>&nbsp;</a>
    <a href="/pages/about" data-no-turbolink>
        <button type="button" class="btn btn-default nav-btn">About Me</button>
    </a>
    <a href="/" data-no-turbolink>
        <button type="button" class="btn btn-default nav-btn">My Work</button>
    </a>
</div>